### ISSUE TITLE
Automate build and release process

### ISSUE THREAD

**Issue by HolgerKache** [cloudant-labs/kafka-connect-cloudant#10]
Use travis and follow examples we have in other projects, e.g.

https://github.ibm.com/dap/streams-services/blob/master/.travis.yml
https://github.com/cloudant-labs/cloudant-python/blob/master/.travis.yml

**Comment by alfinkel** [comment]
@HolgerKache just a heads up, I wouldn't use the `cloudant-python` library as a template/example for anything.  We no longer support that library and instead we support https://github.com/cloudant/python-cloudant.  I don't think in this case it matters much but I figured I'd let you know.

**Comment by HolgerKache** [comment]
@alfinkel Thanks Al! I was literally browsing projects within cloudant-labs to find a better example to no avail. Do you know of one that actively builds releases? https://github.com/cloudant-labs/spark-cloudant does but through Jenkins. I need a Travis example.

**Comment by alfinkel** [comment]
I don't know about automating the release itself through Travis.  That's not something that I've seen before.  I'm not saying that it's not possible, it's just that I haven't done it.  What I've used the Travis CI for is the building and testing of the artifiact each time a new commit or PR is made.  For that you can use any of the Cloudant client library repos as good examples.  Probably https://github.com/cloudant/java-cloudant might be useful since it looks like this repo is Java.

**Comment by asarantes** [comment]
Automated build and release created
