### ISSUE TITLE
Enable IAM API key autontication for Cloudant Kafka Connect

### ISSUE THREAD

**Issue by mohamedih** [cloudant-labs/kafka-connect-cloudant#47]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
Cloudant Kafka Connect support only the username and password authentication. This contribution is to add IAM API Key as an option in the connect to establish the connection with Cloudant via the API Key.
### 2. What you expected to happen
New Code will be added to introduce the IAM API key authentication feature. I have the code fixed and I'm ready to open PR.

**Comment by ricellis** [comment]
Thanks for requesting this feature and offering to contribute.

We need to base this connector on [`cloudant-java-sdk`](https://github.com/IBM/cloudant-java-sdk/) instead of [`java-cloudant`](https://github.com/cloudant/java-cloudant) because of the deprecation of the latter. It makes sense for us to complete that work first such that we are able to add IAM support using the built-ins from `cloudant-java-sdk` instead of using `java-cloudant`. This will avoid us adding IAM support twice and creating more live code that uses an obsolete mechanism since `java-cloudant` uses a Cloudant internal API for its IAM auth that is going to be removed.

**Comment by mohamedih** [comment]
Thank you!!
I'm willing to contribute in this effort. Please let me know when you are ready to start and I will jump in.

**Comment by ricellis** [comment]
The config props necessary for IAM authentication were included with a bunch of other config property updates needed to work withthe new base client and merged in #70 and will be available in the next release.

**Comment by ricellis** [comment]
>will be available in the next release

IAM API key auth as well as [other IAM auth types](https://github.com/IBM/cloudant-kafka-connector/blob/v0.200.0/docs/configuration-reference-sink.md#authentication) are available in the [0.200.0 release](https://github.com/IBM/cloudant-kafka-connector/releases/tag/v0.200.0).
